cursor #e2e2e2
cursor_text_color #c0c8c9

foreground            #e2e2e2
background            #121414
selection_foreground  #253335
selection_background  #bac9cb
url_color             #a6ced3

color0   #121414
color1   #f26d9b
color2   #69d373
color3   #fff572
color4   #95c2c8
color5   #779ea3
color6   #a6ced3
color7   #d0dcdd
color8   #3c4445
color9   #ff9fc0
color10  #a4fdac
color11  #fff8a5
color12  #bee3e8
color13  #d8faff
color14  #e6fcff
color15  #f8feff
