cursor #dfe4dd
cursor_text_color #c0c9c0

foreground            #dfe4dd
background            #0f1511
selection_foreground  #213528
selection_background  #b5ccba
url_color             #93d5aa

color0   #0f1511
color1   #f4946e
color2   #6ad56c
color3   #fff172
color4   #7fca99
color5   #2a623e
color6   #93d5aa
color7   #d2dfd7
color8   #808a83
color9   #ffba9f
color10  #a5ffa7
color11  #fff6a5
color12  #aceac2
color13  #c7ffda
color14  #dbffe7
color15  #f8fffa
